#!/bin/bash
#
amixer set 'Internal Rate' '48kHz'
amixer set 'Internal Rate Multiple' '2.0x'
#
amixer set 'ASRC In' 'DAI 1'
amixer set 'ASRC Out' 'DAI 1'
# DAI 1 ---> Headphone:
amixer set 'DAC Mux' 'CH 0_1'
amixer set 'Headphone' '75%'
amixer set 'DAC Mute' 'off'
# DAI 1 ---> Speaker:
amixer set 'Speaker Mux' 'CH 0_1'
amixer set 'Speaker' '85%'
amixer set 'Speaker Mute' 'off'
# Set up Headset:
amixer set 'Manual Mic Bias' 'off'
amixer set 'Headphone Detection' 'on'
amixer set 'Headset OMTP/CTIA' 'on'
amixer set 'Ring/Sleeve Auto' 'on'
amixer set 'Input Boost Channel 0 Mux' 'Input 3'
amixer set 'Input Boost Channel 1 Mux' 'Input 3'
amixer set 'Input Boost Channel 0' '20dB'
amixer set 'Input Boost Channel 1' '20dB'
amixer set 'ADC Channel 0 Mux' 'Input Boost'
amixer set 'ADC Channel 1 Mux' 'Input Boost'
amixer set 'Input Processor Channel 0 Mux' 'ADC'
amixer set 'Input Processor Channel 1 Mux' 'ADC'
amixer set 'Input Channel 0 Mute' 'off'
amixer set 'Input Channel 1 Mute' 'off'
amixer set 'Input Channel 0' '100%'
amixer set 'Input Channel 1' '100%'
amixer set 'Input Channel 0 PGA Mute' 'off'
amixer set 'Input Channel 1 PGA Mute' 'off'
amixer set 'Input Channel 0 PGA' '0%'
amixer set 'Input Channel 1 PGA' '0%'
amixer set 'DAI 1 Out Mux' 'ADC/DMic 1'
amixer set 'Headphone Auto Switching' 'Speaker'
# Set up Microphone:
amixer set 'Input Boost Channel 0 Mux' 'Input 2'
amixer set 'Input Boost Channel 1 Mux' 'Input 2'
amixer set 'Input Boost Channel 0' '20dB'
amixer set 'Input Boost Channel 1' '20dB'
amixer set 'ADC Channel 0 Mux' 'Input Boost'
amixer set 'ADC Channel 1 Mux' 'Input Boost'
amixer set 'Input Processor Channel 0 Mux' 'ADC'
amixer set 'Input Processor Channel 1 Mux' 'ADC'
amixer set 'Input Channel 0 Mute' 'off'
amixer set 'Input Channel 1 Mute' 'off'
amixer set 'Input Channel 0' '100%'
amixer set 'Input Channel 1' '100%'
amixer set 'Input Channel 0 PGA Mute' 'off'
amixer set 'Input Channel 1 PGA Mute' 'off'
amixer set 'Input Channel 0 PGA' '0%'
amixer set 'Input Channel 1 PGA' '0%'
amixer set 'DAI 1 Out Mux' 'ADC/DMic 1'

